# Generated by Django 3.0.5 on 2020-08-04 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('quicksell', models.IntegerField(max_length=10)),
                ('image', models.ImageField(upload_to='cards')),
                ('chance', models.IntegerField(max_length=10)),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2020, 8, 4, 21, 26, 38, 501561))),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('prescript', models.TextField(max_length=105)),
                ('cost', models.IntegerField(max_length=10)),
                ('icon', models.ImageField(upload_to='packs')),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2020, 8, 4, 21, 26, 38, 392179))),
            ],
            options={
                'verbose_name': 'Пак',
                'verbose_name_plural': 'Паки',
            },
        ),
    ]
