# Generated by Django 3.0.5 on 2020-08-11 07:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('quicksell', models.IntegerField()),
                ('image', models.ImageField(upload_to='cards')),
                ('raiting', models.IntegerField()),
                ('typecard', models.CharField(max_length=10)),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2020, 8, 11, 14, 22, 12, 712351))),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='ChanceForPacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two', models.CharField(max_length=30)),
                ('five', models.CharField(max_length=30)),
                ('twelve', models.CharField(max_length=30)),
                ('twenty_eight', models.CharField(max_length=30)),
                ('fourty', models.CharField(max_length=30)),
                ('fifty', models.CharField(max_length=30)),
                ('sixty_four', models.CharField(max_length=30)),
                ('eighty_two', models.CharField(max_length=30)),
                ('hundred', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Шанс пака',
                'verbose_name_plural': 'Шансы паков',
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('prescript', models.TextField(max_length=105)),
                ('cost', models.IntegerField()),
                ('icon', models.ImageField(upload_to='packs')),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2020, 8, 11, 14, 22, 12, 821349))),
                ('chance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='packs.ChanceForPacks')),
            ],
            options={
                'verbose_name': 'Пак',
                'verbose_name_plural': 'Паки',
            },
        ),
    ]
