# Generated by Django 3.0.5 on 2020-08-11 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 18, 26, 40, 983343)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 18, 26, 41, 81350)),
        ),
    ]
