# Generated by Django 3.0.5 on 2020-08-04 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='chance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 21, 27, 44, 110928)),
        ),
        migrations.AlterField(
            model_name='card',
            name='quicksell',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pack',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pack',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 21, 27, 44, 1560)),
        ),
    ]
