# Generated by Django 3.0.5 on 2020-08-13 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_auto_20200811_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 19, 41, 39410)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 19, 41, 158417)),
        ),
    ]
